config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:create, :destroy] do
      # Adding the report route for comments
      post :report, on: :member  # This will map to /posts/:post_id/comments/:id/report
    end
    resources :likes, only: [:create, :destroy]
  end

  devise_for :users
  resources :users, only: [] do
    member do
      post :report
      delete 'cancel_account', to: 'users#destroy', as: :cancel_account
      get :posts, to: 'users#posts', as: :posts
    end
  end

  # Add route for reporting comments separately (in case you want it outside of posts)
  resources :comments, only: [] do
    member do
      post :report  # This will map to /comments/:id/report
    end
  end

  # Define other routes
  root "posts#index"
  get "home/about"

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  # Other routes like PWA can be added here if needed

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
  
    if @comment.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.append("comments-#{@post.id}",
                                partial: "comments/comment",
                                locals: { comment: @comment, post: @post }),
  
            turbo_stream.replace("comment-count-#{@post.id}",
                                 partial: "comments/comment_count",
                                 locals: { post: @post })
          ]
        end
        format.html { redirect_to @post, notice: 'Comment was successfully posted.' }
      end
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
  

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
  
    if @comment.user == current_user || current_user.admin?
      @comment.destroy
  
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            # Remove the comment from the DOM
            turbo_stream.remove("comment-#{@comment.id}"),
            
            # Replace the comment count with updated content
            turbo_stream.replace("comment-count-#{@post.id}",
                                 partial: "comments/comment_count",
                                 locals: { post: @post })
          ]
        end
        format.html { redirect_to @post, notice: "Comment was successfully deleted." }
      end
    else
      redirect_to @post, alert: "You are not authorized to delete this comment." and return
    end
  end  

  def report
    @comment = Comment.find(params[:id])
  
    if @comment
      @comment.update(reported: true)  # Set the reported status to true
      @comment.user.increment!(:flags)  # Optionally increment the flag count for the user
  
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("comment-#{@comment.id}", locals: { comment: @comment })
        end
        format.html { redirect_back(fallback_location: root_path, notice: "User reported successfully.") }
      end
    else
      flash[:alert] = "Could not report the comment."
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>" class="comment-wrapper">
  <div class="comment-line">
    <%= link_to posts_user_path(comment.user), class: "username-link" do %>
      <strong><%= comment.user&.username || "Anonymous" %></strong>
    <% end %>

    <div class="dropdown comment-dropdown">
      <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton-<%= comment.id %>" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="fa-solid fa-ellipsis-vertical"></i>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton-<%= comment.id %>">
        <% if comment.user == current_user %>
          <%= button_to "Delete", post_comment_path(post, comment), method: :delete, remote: true, class: "dropdown-item", data: { confirm: "Are you sure?" } %>
        <% end %>
        <%= button_to "Report User", report_comment_path(comment), method: :post, class: "dropdown-item", data: { confirm: "Are you sure you want to report this comment?" } %>
      </ul>
    </div>
  </div>

  <div class="comment-content">
    <%= comment.content %>
  </div>
</div>

app/views/comments/_comment_count.html.erb
<span id="comment-count-<%= post.id %>" class="comment-count">
  <%= post.comments.size %>
</span>

app/views/comments/create.js.erb
// Append the new comment to the comments list
$("#comments-<%= @post.id %>").append("<%= j render @comment %>");

// Clear the comment textarea
$("#new-comment-form-<%= @post.id %> textarea").val("");

// Update the comment count
$("#comment-count-<%= @post.id %>").text("<%= @post.comments.size %>");

app/views/comments/destroy.js.erb
// Remove the deleted comment from the DOM
$('#comment-<%= @comment.id %>').remove();

// Update the comment count
$('#comment-count-<%= @post.id %>').text('<%= @post.comments.size %>');