config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:create, :destroy] do
      # Adding the report route for comments
      post :report, on: :member  # This will map to /posts/:post_id/comments/:id/report
    end
    resources :likes, only: [:create, :destroy]
  end

  devise_for :users
  resources :users, only: [] do
    member do
      post :report
      delete 'cancel_account', to: 'users#destroy', as: :cancel_account
      get :posts, to: 'users#posts', as: :posts
    end
  end

  # Add route for reporting comments separately (in case you want it outside of posts)
  resources :comments, only: [] do
    member do
      post :report  # This will map to /comments/:id/report
    end
  end

  # Define other routes
  root "posts#index"
  get "home/about"

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  # Other routes like PWA can be added here if needed

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:index, :show, :edit, :new]
  before_action :authorize_user!, only: [:destroy, :edit, :update]

  # GET /posts or /posts.json
  def index
    @posts = Post.includes(:comments).order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post = Post.find(params[:id])
  
    if @post.user == current_user || current_user.admin?
      @post.destroy!
  
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            # Remove the post from the DOM
            turbo_stream.remove("post-#{@post.id}"),
          
          ]
        end
        format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully deleted." }
      end
    else
      redirect_to posts_path, alert: "You are not authorized to delete this post." and return
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.expect(post: [ :text, :user_id ])
    end

    def authorize_user!
      unless @post.user == current_user  || current_user.admin?
        redirect_to posts_path, notice: "You can only edit, update, delete your own posts."
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_area :text, class: "comment-textarea", placeholder: "Whats on your mind?" %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="uc-submit-form">
    <%= form.submit class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <div class="comment-line">
    <!-- Post User and Timestamp -->
    <div class="created-at">
      <%= link_to posts_user_path(post.user), class: "username-link" do %>
        <strong>
          <%= post.user&.username || "Anonymous" %>
        </strong>
      <% end %>
      <p>
        <small><%= post.created_at.strftime("%B %d, %Y at %I:%M %p") %></small>
      </p>
    </div>

    <!-- Dropdown for Post Actions -->
    <div class="dropdown post-options-dropdown">
      <button class="btn btn-link dropdown-toggle" type="button" id="postOptionsDropdown-<%= post.id %>" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="fa-solid fa-ellipsis-vertical"></i>
      </button>
      <ul class="dropdown-menu" aria-labelledby="postOptionsDropdown-<%= post.id %>">
        <% if post.user == current_user || current_user.admin? %>
          <li><%= link_to "Edit Post", edit_post_path(post), class: "dropdown-item" %></li>
          <li>
            <%= button_to "Delete Post", post, method: :delete, class: "dropdown-item", data: { confirm: "Are you sure you want to delete this post?" }, remote: true %>
          </li>
        <% else %>
          <li></li>
        <% end %>
        <%= turbo_frame_tag "report_post_#{post.id}" do %>
          <%= button_to "Report User", report_user_path(post.user), method: :post, class: "dropdown-item", data: { turbo_frame: "report_post_#{post.id}" } %>
        <% end %>
      </ul>
    </div>
  </div>

  <!-- Post Content -->
  <p>
    <%= post.text %>
  </p>
</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<div id="edit-wrapper">
    <h2>Edit post</h2>


  <div id="cu-post-wrapper">
    <%= render "form", post: @post %>
  </div>
  
</div>

app/views/posts/index.html.erb
<%= link_to new_post_path, id: "new-post-btn", data: { turbo_frame: "new_post_form" } do %>
  <div id="add-new-post" class="post-instance">
    <i class="fa-regular fa-square-plus"></i>
    New post
  </div>
<% end %>

<div id="posts">
  <% @posts.each_with_index do |post, index| %>
    <div class="post-instance" id="post-<%= post.id %>">
        <%= render post %>



      <div class="reactions">
        <%= turbo_frame_tag "like_button_#{post.id}" do %>
          <% if post.liked_users.include?(current_user) %>
            <%= button_to post_like_path(post, post.likes.find_by(user: current_user)), 
                          method: :delete, 
                          class: "btn btn-link like-btn", 
                          data: { turbo_stream: true } do %>
              <i class="fa-solid fa-heart"></i>
              <span class="comment-count"><%= post.likes.size %></span>
            <% end %>
          <% else %>
            <%= button_to post_likes_path(post), 
                          method: :post, 
                          class: "btn btn-link like-btn", 
                          data: { turbo_stream: true } do %>
              <i class="fa-regular fa-heart"></i>
              <span class="comment-count"><%= post.likes.size %></span>
            <% end %>
          <% end %>
        <% end %>

        <!-- Comment Icon with Comment Count -->
        <button class="btn btn-link comment-toggle-btn" data-bs-toggle="collapse" data-bs-target="#collapse-<%= index %>">
          <i class="fa-solid fa-comment-dots"></i>
          <span id="comment-count-<%= post.id %>" class="comment-count"><%= post.comments.size %></span>
        </button>
      </div>

      <!-- Accordion for Comments -->
      <div class="accordion" id="accordion-<%= index %>">
        <div class="accordion-item">
          <div id="collapse-<%= index %>" class="accordion-collapse collapse" aria-labelledby="heading-<%= index %>">
            <div class="accordion-body">
              <div id="comments-<%= post.id %>">
                <% post.comments.order(created_at: :asc).limit(10).each do |comment| %>
                  <div class="comment-wrapper" id="comment-<%= comment.id %>">
                    <div class="comment-line">
                      <div class="created-at">
                        <%= link_to posts_user_path(comment.user), class: "username-link" do %>
                          <strong><%= comment.user.username %></strong>
                        <% end %>
                        <p>
                          <small><%= comment.created_at.strftime("%B %d, %Y at %I:%M %p") %></small>
                        </p>
                      </div>
                      <!-- Ellipsis Dropdown Icon -->
                      <div class="dropdown">
                        <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton-<%= comment.id %>" data-bs-toggle="dropdown" aria-expanded="false">
                          <i class="fa-solid fa-ellipsis-vertical"></i>
                        </button>

                        <!-- Dropdown Menu -->
                        <ul class="dropdown-menu comments-dropdown" aria-labelledby="dropdownMenuButton-<%= comment.id %>">
                          <% if comment.user == current_user || current_user.admin?  %>
                            <li><%= button_to "Delete", post_comment_path(post, comment), method: :delete, class: "dropdown-item", data: { confirm: "Are you sure?" } %></li>
                          <% end %>
                          <!-- Report Comment Button -->
                          <%= turbo_frame_tag "report_comment_#{comment.id}" do %>
                            <%= button_to "Report User", report_user_path(comment.user), method: :post, class: "dropdown-item", data: { turbo_frame: "report_comment_#{comment.id}" } %>
                          <% end %>
                        </ul>
                      </div>
                    </div>

                    <!-- Comment Content -->
                    <div class="comment-content">
                      <%= comment.content %>
                    </div>
                  </div>
                <% end %>
              </div>

              <!-- "Show more" link always at the bottom -->
              <% if post.comments.count > 10 %>
                <div id="show-more-container-<%= post.id %>">
                  <%= link_to post_path(post), class: "comment-wrapper", id: "show-more" do %>
                    <span>Show more</span>
                  <% end %>
                </div>
              <% end %>

              <!-- Turbo Frame for Comment Form -->
              <% if user_signed_in? %>
                <%= turbo_frame_tag "new_comment_#{post.id}" do %>
                  <%= form_with(model: [post, Comment.new], local: false, id: "new-comment-form-#{post.id}") do |form| %>
                    <div class="post-comment-wrapper">
                      <%= form.text_area :content, class: "comment-textarea", placeholder: "Add a comment" %>
                      <div class="button-container">
                        <%= form.submit "Post Comment", class: "post-comment-btn btn btn-primary" %>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              <% else %>
                <p>You must be <%= link_to "logged in", new_user_session_path %> to comment.</p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<div id="edit-wrapper">
  <div id="edit-user-header">
    <h2>New post</h2>
  </div>

  
  <div id="cu-post-wrapper">

    <%= render "form", post: @post %>

  </div>
</div>

app/views/posts/show.html.erb
<button id="scroll-to-bot"><i class="fa-solid fa-down-long"></i></button>
<div class="post-instance" id="post-<%= @post.id %>">
  <!-- Top-Right Dropdown for Post Actions -->
  <div class="dropdown post-options-dropdown">
    <button class="btn btn-link dropdown-toggle" type="button" id="postOptionsDropdown-<%= @post.id %>" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="fa-solid fa-ellipsis-vertical"></i> <!-- Ellipsis icon -->
    </button>
    <ul class="dropdown-menu" aria-labelledby="postOptionsDropdown-<%= @post.id %>">
      <% if @post.user == current_user %>
        <li><%= link_to "Edit Post", edit_post_path(@post), class: "dropdown-item" %></li>
        <li><%= button_to "Delete Post", @post, method: :delete, remote: true, class: "dropdown-item", data: { confirm: "Are you sure you want to delete this post?" } %></li>
      <% end %>
      <!-- Report Post Button -->
      <li>
        <%= turbo_frame_tag "report_post_#{@post.id}" do %>
          <%= button_to "Report User", report_user_path(@post.user), method: :post, class: "dropdown-item", data: { turbo_frame: "report_post_#{@post.id}" } %>
        <% end %>      
      </li>
    </ul>
  </div>

  <!-- Render Post Content -->
  <%= render @post %>

  <!-- Reaction Icons -->
  <div class="reactions">
    <%= turbo_frame_tag "like_button_#{@post.id}" do %>
      <% if @post.liked_users.include?(current_user) %>
        <%= button_to post_like_path(@post, @post.likes.find_by(user: current_user)), 
                      method: :delete, 
                      class: "btn btn-link like-btn", 
                      data: { turbo_stream: true } do %>
          <i class="fa-solid fa-heart"></i>
          <span class="comment-count"><%= @post.likes.size %></span>
        <% end %>
      <% else %>
        <%= button_to post_likes_path(@post), 
                      method: :post, 
                      class: "btn btn-link like-btn", 
                      data: { turbo_stream: true } do %>
          <i class="fa-regular fa-heart"></i>
          <span class="comment-count"><%= @post.likes.size %></span>
        <% end %>
      <% end %>
    <% end %>




    <button class="btn btn-link comment-toggle-btn">
      <i class="fa-solid fa-comment-dots"></i>
      <span class="comment-count" id="comment-count-<%= @post.id %>"><%= @post.comments.size %></span>
    </button>
  </div>

  <!-- Turbo Frame for Comments Section -->
  <%= turbo_frame_tag "post_#{@post.id}_comments" do %>
    <!-- Show All Comments -->
    <div id="comments-<%= @post.id %>">
      <% @post.comments.each do |comment| %>
        <div id="comment-<%= comment.id %>" class="comment-wrapper">
          <div class="comment-line">
            <%= turbo_frame_tag "post_#{@post.id}_comments", data: { turbo: false } do %>
              <%= link_to posts_user_path(comment.user), class: "username-link" do %>
                <strong><%= comment.user.username || "Anonymous" %></strong>
              <% end %>
            <% end %>


            <!-- Dropdown for Comment Actions -->
            <div class="dropdown comment-dropdown">
              <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton-<%= comment.id %>" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa-solid fa-ellipsis-vertical"></i>
              </button>
              <ul class="dropdown-menu comments-dropdown" aria-labelledby="dropdownMenuButton-<%= comment.id %>">
                <% if comment.user == current_user || current_user.admin? %>
                  <li><%= button_to "Delete", post_comment_path(@post, comment), method: :delete, remote: true, class: "dropdown-item", data: { confirm: "Are you sure?" } %></li>
                <% end %>
                <!-- Report Comment Button -->
                
                <li>
                  <%= turbo_frame_tag "report_post_#{@post.id}" do %>
                    <%= button_to "Report User", report_user_path(comment.user), method: :post, class: "dropdown-item", data: { turbo_frame: "report_post_#{@post.id}" } %>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>

          <!-- Comment Content -->
          <div class="comment-content">
            <%= comment.content %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <!-- Turbo Frame for New Comment Form -->
  <% if user_signed_in? %>
    <%= turbo_frame_tag "new_comment_#{@post.id}" do %>
      <%= form_with(model: [@post, Comment.new], local: false, id: "new-comment-form-#{@post.id}") do |form| %>
        <div class="post-comment-wrapper">
          <%= form.text_area :content, class: "comment-textarea", placeholder: "Add a comment" %>
          <div class="button-container">
            <%= form.submit "Post Comment", class: "post-comment-btn btn btn-primary" %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <p>You must be <%= link_to "logged in", new_user_session_path, class: "login-link" %> to comment.</p>
  <% end %>
</div>

<script>
  const scrollButton = document.getElementById('scroll-to-bot');

  window.addEventListener('scroll', toggleButton);

  function toggleButton() {
    if (window.scrollY < document.body.scrollHeight / 2) {
      scrollButton.innerHTML = '<i class="fa-solid fa-down-long"></i>';
      scrollButton.onclick = () => {
        window.scrollTo({
          top: document.body.scrollHeight,
          behavior: 'smooth'
        });
      };
    } else {
      scrollButton.innerHTML = '<i class="fa-solid fa-up-long"></i>';
      scrollButton.onclick = () => {
        window.scrollTo({
          top: 0,
          behavior: 'smooth'
        });
      };
    }
  }


  toggleButton(); 
</script>